### ISSUE TITLE
Caffeinated Fails to Load Assets When Google Fonts Fails to Load

### ISSUE THREAD

**Issue by SwissWriter** [thehelvijs/Caffeinated#15]
![image](https://user-images.githubusercontent.com/72187675/94776437-b6fa5d80-038f-11eb-8331-92f00605e524.png)

Google was down when this bug occurred. Caffeine loads into its box but there's no texts and buttons to interact with. Top left shows that user's logged in. All tabs (e.g. Settings, Chat, etc.) can be clicked but there's nothing in there.

**Comment by e3ndr** [comment]
To clarify: The error occured since read fonts before loading overlays

**Comment by e3ndr** [comment]
Closing, this was fixed in the beta.
