### ISSUE TITLE
Flag / Highlight comments (enhancement)

### ISSUE THREAD

**Issue by JimmyKip** [thehelvijs/Caffeinated#44]
Enhancement request, not issue - if you're not after suggestions please close.

Caffeine's comment handling is poor; if a lot of chat is happening the caster can be responding to a comment that viewers can no longer see.

In the Caffeinated chat module, as well as respond, upvote or open-link add another option that can flag & extract the message in some way such that it can then be isolated and inserted into OBS as a discrete Scene Source where it can be used in an overlay. 

Coupled with a configurable timer for the flag this would give a caster more control over the duration any given comment would be displayed & visible to viewers.

**Comment by e3ndr** [comment]
> Enhancement request, not issue - if you're not after suggestions please close.

We're always after suggestions :)

> Caffeine's comment handling is poor; if a lot of chat is happening the caster can be responding to a comment that viewers can no longer see.
\
In the Caffeinated chat module, as well as respond, upvote or open-link add another option that can flag & extract the message in some way such that it can then be isolated and inserted into OBS as a discrete Scene Source where it can be used in an overlay.
\
Coupled with a configurable timer for the flag this would give a caster more control over the duration any given comment would be displayed & visible to viewers.

~~Definitely will implement this, not only useful for Caffeine but other sites as well.~~

~~Not going to give a deadline for this, but it will definitely happen before `1.2`.~~

**Comment by e3ndr** [comment]
Upon rethought, I don't think we'll do this. Sorry, but there's a lot to implement.
