### ISSUE TITLE
Chat seems to work only on first launch

### ISSUE THREAD

**Issue by Glitch3dPenguin** [thehelvijs/Caffeinated#6]
On the latest release it seems that the chat feature is only working when you first launch the program. On any launch after I have not been able to get chat to work or see new messages.

**Comment by thehelvijs** [comment]
@mteverst it does not appear in OBS or at all? There is a known issue where Caffeinated has to launched before OBS for it to work (or when Caffeinated is launched, refresh cache in Browser source).

**Comment by e3ndr** [comment]
This was fixed in 0.4, closing.
